---
apiVersion: v1
kind: Service
metadata:
  name: ceph-test-dashboard
  namespace: ${DASHBOARD_NAMESPACE}
  labels:
    app.kubernetes.io/name: ceph-test-dashboard
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ceph-test-dashboard
  ports:
    - name: http
      port: 8501
      targetPort: http
      protocol: TCP
